# Generated by Django 5.2.17 on 2026-09-13 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('rubber', 'Scrap Rubber'), ('textile', 'Textile Remnants'), ('coconut', 'Coconut Shells'), ('plastic', 'Plastic Fragments'), ('fish', 'Fish Scales')], max_length=20)),
                ('price_per_ton', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume_tons', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purity_percent', models.PositiveSmallIntegerField()),
                ('trust_score', models.PositiveSmallIntegerField(default=80)),
                ('location', models.CharField(max_length=255)),
                ('permit_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_requested', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='marketplace.materiallisting')),
            ],
        ),
    ]
