# Generated by Django 5.2.17 on 2026-09-14 18:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_permit_document_company_verified_at_and_more'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('material_name', models.CharField(default='Shredded Tyre Crumb Rubber', max_length=200)),
                ('buyer_name', models.CharField(default='Ahmedabad Infrastructure Co.', max_length=200)),
                ('target_volume_tons', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('collected_volume_tons', models.DecimalField(decimal_places=2, default=360.0, max_digits=10)),
                ('status', models.CharField(choices=[('filling', 'Filling'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='filling', max_length=20)),
                ('contributing_suppliers_count', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('standard_price_per_ton', models.DecimalField(decimal_places=2, default=20000.0, max_digits=10)),
                ('carbon_offset_factor', models.DecimalField(decimal_places=2, default=1.65, help_text='kg CO₂e avoided per kg/ton of byproduct reused', max_digits=8)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Material Categories',
            },
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='batch_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='compliance_id',
            field=models.CharField(default='GPCB-WM-22910', max_length=100),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='contamination_percent',
            field=models.DecimalField(decimal_places=2, default=0.4, max_digits=5),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='moisture_percent',
            field=models.DecimalField(decimal_places=2, default=1.8, max_digits=5),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='moq_tons',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum Order Quantity (tons)', max_digits=8),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='packaging_type',
            field=models.CharField(default='Woven poly bulk bags, 500 kg', max_length=150),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='particle_size',
            field=models.CharField(default='2–5 mm', max_length=100),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='recommended_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_permit', 'Pending Permit'), ('fulfilled', 'Fulfilled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='buyer_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_orders', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='destination_facility',
            field=models.CharField(blank=True, default='Ahmedabad Plant Site, Gujarat', max_length=255),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='estimated_distance_km',
            field=models.PositiveIntegerField(default=165),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='origin_facility',
            field=models.CharField(blank=True, default='Vapi Industrial Cluster, Gujarat', max_length=255),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='transport_mode',
            field=models.CharField(default='Loose Bulk Truck (20t)', max_length=100),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='materiallisting',
            name='category',
            field=models.CharField(choices=[('rubber', 'Scrap Rubber'), ('textile', 'Textile Remnants'), ('coconut', 'Coconut Shells'), ('plastic', 'Plastic Fragments'), ('fish', 'Fish Scales')], default='rubber', max_length=20),
        ),
        migrations.AlterField(
            model_name='materiallisting',
            name='location',
            field=models.CharField(default='Vapi, Gujarat', max_length=255),
        ),
        migrations.AlterField(
            model_name='materiallisting',
            name='permit_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='materiallisting',
            name='price_per_ton',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materiallisting',
            name='purity_percent',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='materiallisting',
            name='trust_score',
            field=models.PositiveSmallIntegerField(default=85),
        ),
        migrations.AlterField(
            model_name='materiallisting',
            name='volume_tons',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='volume_requested',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255)),
                ('certificate_type', models.CharField(default='Environmental Permit', max_length=100)),
                ('material', models.CharField(default='Industrial Scrap', max_length=150)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='verified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.company')),
            ],
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='marketplace.materialcategory'),
        ),
    ]
