# Generated by Django 5.2.17 on 2026-09-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_aggregationpool_materialcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallisting',
            name='image',
            field=models.FileField(blank=True, help_text='Upload waste stream batch photo (JPG, PNG, WebP)', null=True, upload_to='listings/'),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='quality_certificate',
            field=models.FileField(blank=True, help_text='Chemical lab test report & purity certificate', null=True, upload_to='quality_certs/'),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='quality_grade',
            field=models.CharField(choices=[('grade_a', 'Grade A - Certified Lab Tested'), ('grade_b', 'Grade B - Secondary Feedstock'), ('grade_c', 'Grade C - Raw Unsorted Byproduct')], default='grade_a', max_length=20),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='sampling_protocol',
            field=models.CharField(default='Standard Composite Sampling per ASTM D6323 with pre-dispatch retention sample held', max_length=255),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='current_location',
            field=models.CharField(default='NH 544 Aluva Bypass, En route to Palakkad', max_length=255),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='delivery_status',
            field=models.CharField(choices=[('order_confirmed', 'Order Confirmed & Escrow Reserved'), ('quality_inspected', 'Factory Weighbridge & Quality Inspected'), ('in_transit', 'In Transit Along Highway Corridor'), ('delivered', 'Delivered & Weighment Verified')], default='in_transit', max_length=30),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='driver_contact',
            field=models.CharField(default='+91 98460 22100 (Kerala Freight Carriers)', max_length=50),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='eta_hours',
            field=models.CharField(default='3.5 Hours', max_length=50),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='tracking_progress_percent',
            field=models.PositiveIntegerField(default=65),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='vehicle_number',
            field=models.CharField(default='KL-07-BW-4921 (20t Closed Container Truck)', max_length=50),
        ),
        migrations.AlterField(
            model_name='materiallisting',
            name='compliance_id',
            field=models.CharField(default='KPCB-WM-22910', max_length=100),
        ),
        migrations.AlterField(
            model_name='materiallisting',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='materiallisting',
            name='location',
            field=models.CharField(default='Kochi, Kerala', max_length=255),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='destination_facility',
            field=models.CharField(blank=True, default='Palakkad Manufacturing Complex, Kerala', max_length=255),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='estimated_distance_km',
            field=models.PositiveIntegerField(default=142),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='origin_facility',
            field=models.CharField(blank=True, default='Kochi Industrial Belt, Kerala', max_length=255),
        ),
    ]
