# Generated by Django 5.2.17 on 2026-09-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_materiallisting_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallisting',
            name='lab_accreditation_number',
            field=models.CharField(blank=True, default='NABL-KL-2026/TC-8812', help_text='Accredited testing laboratory certification reference ID', max_length=100),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='lab_audit_status',
            field=models.CharField(choices=[('audited_verified', 'Audited & Lab Verified'), ('pending_audit', 'Pending Lab Audit'), ('self_declared', 'Supplier Self-Declared')], default='audited_verified', max_length=25),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='checkpoint_toll',
            field=models.DecimalField(decimal_places=2, default=450.0, help_text='Paliakkara/Highway Corridor Toll & Border Clearance', max_digits=8),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='transport_mode',
            field=models.CharField(default='Closed Container Bulk Carrier (20t)', max_length=100),
        ),
    ]
