# Generated by Django 5.2.17 on 2026-09-21 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_email_otp_company_is_email_verified'),
        ('marketplace', '0004_materiallisting_lab_accreditation_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallisting',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Admin Review'), ('approved', 'Approved & Live on Marketplace'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='condition',
            field=models.CharField(choices=[('Recyclable Clean', 'Recyclable Clean'), ('Unsorted Bulk', 'Unsorted Bulk'), ('Reconditioned', 'Reconditioned'), ('Processed Scrap', 'Processed Scrap')], default='Recyclable Clean', max_length=50),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed material composition, source process, and usage recommendations'),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='mismatch_warning',
            field=models.CharField(blank=True, default='', help_text='Consistency checking alert if category conflicts with name/image', max_length=255),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='quantity_unit',
            field=models.CharField(choices=[('Tons', 'Tons'), ('Kg', 'Kilograms'), ('Litres', 'Litres')], default='Tons', max_length=20),
        ),
        migrations.AlterField(
            model_name='materiallisting',
            name='volume_tons',
            field=models.DecimalField(decimal_places=2, help_text='Total available quantity', max_digits=10),
        ),
        migrations.CreateModel(
            name='FundingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Circular Recycling Infrastructure', max_length=100)),
                ('description', models.TextField()),
                ('target_amount', models.DecimalField(decimal_places=2, default=500000.0, max_digits=12)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=120000.0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active Funding'), ('funded', 'Fully Funded'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_projects', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Additional angle photo', upload_to='listing_gallery/')),
                ('caption', models.CharField(blank=True, default='Angle View', max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='marketplace.materiallisting')),
            ],
        ),
        migrations.CreateModel(
            name='ReportedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Reason for reporting (e.g. Misleading image, Wrong category, Impure sample)', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.materiallisting')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
