# Generated by Django 5.2.17 on 2026-09-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_materiallisting_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='payment_status',
            field=models.CharField(choices=[('escrow_held', 'Buyer Escrow Held (Pending Supplier Approval)'), ('released_to_supplier', 'Released to Supplier (Dispatched)'), ('refunded', 'Refunded to Buyer')], default='escrow_held', max_length=30),
        ),
        migrations.AlterField(
            model_name='aggregationpool',
            name='buyer_name',
            field=models.CharField(default='Kochi Infrastructure & Industrial Corp.', max_length=200),
        ),
    ]
