# Generated by Django 5.2.17 on 2026-09-22 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_procurementrequest_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investor_name', models.CharField(blank=True, default='', max_length=150)),
                ('benefit_tier', models.CharField(choices=[('feedstock_discount', 'Offtake Discount Tier (8% Feedstock Discount + Supply Priority)'), ('priority_quota', 'Priority Quota Tier (Guaranteed Supply During Raw Material Scarcity)'), ('carbon_insetting', 'Carbon Insetting Tier (Certified Scope-3 Avoided Emissions Offset)')], default='feedstock_discount', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circular_pledges', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='marketplace.fundingproject')),
            ],
        ),
    ]
