# Generated by Django 5.2.17 on 2026-09-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_projectpledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallisting',
            name='image_detected_category',
            field=models.CharField(blank=True, default='', help_text='Detected waste category based on image visual signature', max_length=100),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='image_verification_score',
            field=models.FloatField(default=0.0, help_text='Confidence match score percentage (0-100%) based on visual features'),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='image_verification_status',
            field=models.CharField(choices=[('Likely Match', 'Likely Match'), ('Manual Review', 'Manual Verification Required'), ('Possible Mismatch', 'Possible Mismatch')], default='Manual Review', help_text='Automated preliminary image content verification status', max_length=50),
        ),
        migrations.AlterField(
            model_name='materiallisting',
            name='category',
            field=models.CharField(choices=[('rubber', 'Scrap Rubber'), ('textile', 'Textile Remnants'), ('coconut', 'Coconut Shells'), ('plastic', 'Plastic Fragments'), ('fish', 'Fish Scales'), ('paper', 'Paper Waste'), ('metal', 'Metal Scrap')], default='rubber', max_length=20),
        ),
    ]
