# Generated by Django 5.2.17 on 2026-09-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_materiallisting_image_detected_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallisting',
            name='use_category_symbol',
            field=models.BooleanField(default=False, help_text='Automatically set to True if uploaded images fail verification, displaying the official category symbol instead.'),
        ),
    ]
