# Generated by Django 5.2.17 on 2026-09-14 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='permit_document',
            field=models.FileField(blank=True, help_text='Upload business registration certificate or pollution control permit.', null=True, upload_to='permits/'),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('auto_verified', 'Auto Verified'), ('manual_approved', 'Manually Approved'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20),
        ),
    ]
