# Generated by Django 5.2.17 on 2026-09-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_permit_document_company_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='user_type',
            field=models.CharField(choices=[('supplier', 'Supplier / Waste Generator'), ('buyer', 'Buyer / Recycler'), ('both', 'Dual Enterprise (Both Buyer & Supplier)')], max_length=20),
        ),
    ]
