# Generated by Django 5.2.17 on 2026-09-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_otp',
            field=models.CharField(blank=True, default='', help_text='6-digit Email verification OTP code', max_length=6),
        ),
        migrations.AddField(
            model_name='company',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Whether company contact email is verified via OTP'),
        ),
    ]
