# Generated by Django 5.2.17 on 2026-09-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_email_otp_company_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_image',
            field=models.FileField(blank=True, help_text='Enterprise profile picture or company logo.', null=True, upload_to='company_logos/'),
        ),
    ]
